<?php
// $Id$

/**
 * @file
 *
 */

function incubator_announcements_views_api() {
  return array(
    'api' => 3,
  );
}

function incubator_announcements_cron() {
  $q = new EntityFieldQuery();
  $q->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'announcement')
          ->propertyCondition('status', 1)
          ->fieldCondition('field_expires_date', 'value', time(), '<');
  foreach ($q->execute() as $entity_type => $entities) {
    foreach ($entities as $node) {
      db_update('node')->condition('nid', $node->nid)->fields(array('status' => 0))->execute();
    }
  }
}