<?php
// $Id$

/**
 * @file
 *
 */

function incubator_facilities_views_api() {
  return array(
    'api' => 3,
  );
}

function incubator_facilities_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_maps':
        return array('version' => 1);

      case 'openlayers_layers':
        return array('version' => 1);

      case 'openlayers_styles':
        return array('version' => 1);

    }
  }
}

function incubator_facilities_openlayers_map_preprocess_alter(&$map) {
  if (!empty($map['map_name']) && $map['map_name'] == 'incubator_main') {
    $word = 'facilities';
    $layer = "map_{$word}_openlayers_1";
    $map['behaviors']['openlayers_behavior_popup']['layers'][$layer] = $layer;
    $map['behaviors']['openlayers_behavior_tooltip']['layers'][$layer] = 0;
    $map['layers'][$layer] = $layer;
    $map['layer_weight'][$layer] = 0;
    $map['layer_styles'][$layer] = $word;
    $map['layer_styles_select'][$layer] = $word;
    $map['layer_activated'][$layer] = $layer;
    $map['layer_switcher'][$layer] = $layer;
  }
}









function incubator_facilities_openlayers_styles() {
  $t = get_t();
  $items = array();
  $openlayers_styles = new stdClass;
  $openlayers_styles->disabled = FALSE; /* Edit this to true to make a default openlayers_styles disabled initially */
  $openlayers_styles->api_version = 1;
  $openlayers_styles->name = 'facilities';
  $openlayers_styles->title = t('Facilities');
  $openlayers_styles->description = t('Facilities');
  $openlayers_styles->data = array(
    'externalGraphic' => drupal_get_path('module', 'incubator_mapping') . '/gmap-markers/big/blue.png',
    'pointRadius' => 16,
    'fillColor' => '#FFCC66',
    'strokeColor' => '#FF9933',
    'strokeWidth' => 4,
    'fillOpacity' => 0.5,
    'strokeOpacity' => 1,
    'strokeLinecap' => 'round',
    'strokeDashstyle' => 'solid',
    'graphicWidth' => 30,
    'graphicHeight' => 51,
    'graphicOpacity' => 1,
    'graphicXOffset' => -15,
    'graphicYOffset' => -51,
    'labelAlign' => 'cm',
    'labelXOffset' => '0',
    'labelYOffset' => '0',
  );
  $items["facilities"] = $openlayers_styles;
  return $items;
}
