<?php
// $Id$

/**
 * @file
 *
 */

function incubator_mapping_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function incubator_mapping_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_maps':
        return array('version' => 1);
      case 'openlayers_layers':
        return array('version' => 1);
      case 'openlayers_styles':
        return array('version' => 1);
    }
  }
}

function incubator_mapping_openlayers_map_preprocess_alter(&$map) {
  if (!empty($map['map_name']) && $map['map_name'] == 'incubator_main') {
    $map['center']['initial']['centerpoint'] = variable_get('incubator_mapping_centerpoint', '-99, 39');
    $map['center']['initial']['zoom'] = variable_get('incubator_mapping_zoom', '4');
  }
}




// MAPS

function incubator_mapping_openlayers_maps() {
  $t = get_t();
  $items = array();
  $openlayers_maps = new stdClass();
  $openlayers_maps->disabled = FALSE; /* Edit this to true to make a default openlayers_maps disabled initially */
  $openlayers_maps->api_version = 1;
  $openlayers_maps->name = 'incubator_main';
  $openlayers_maps->title = 'Incubator Main Map';
  $openlayers_maps->description = 'The main map for the Incubator project.';
  $openlayers_maps->data = array(
    'width' => 'auto',
    'height' => '400px',
    'image_path' => 'profiles/bahai_incubator/modules/incubator/incubator_mapping/openlayers/theme/default_dark/img/',
    'css_path' => 'profiles/bahai_incubator/modules/incubator/incubator_mapping/openlayers/theme/default_dark/style.css',
    'proxy_host' => '',
    'hide_empty_map' => 0,
    'center' => array(
      'initial' => array(),
      'restrict' => array(
        'restrictextent' => 0,
        'restrictedExtent' => '',
      ),
    ),
    'behaviors' => array(
      'openlayers_behavior_keyboarddefaults' => array(),
      'openlayers_behavior_attribution' => array(
        'separator' => '',
      ),
      'openlayers_behavior_dragpan' => array(),
      'openlayers_behavior_navigation' => array(
        'zoomWheelEnabled' => 0,
        'zoomBoxEnabled' => 1,
        'documentDrag' => 0,
      ),
      'openlayers_behavior_panzoombar' => array(
        'zoomWorldIcon' => 0,
        'panIcons' => 1,
      ),
      'openlayers_behavior_popup' => array(
        'layers' => array(),
        'panMapIfOutOfView' => 0,
        'keepInMap' => 1,
      ),
    ),
    'default_layer' => 'google_normal',
    'layers' => array(
      'google_hybrid' => 'google_hybrid',
      'google_normal' => 'google_normal',
    ),
    'layer_weight' => array(),
    'layer_styles' => array(),
    'layer_activated' => array(),
    'layer_switcher' => array(),
    'projection' => 'EPSG:3857',
    'displayProjection' => 'EPSG:4326',
    'styles' => array(
      'default' => 'default',
      'select' => 'default',
      'temporary' => 'default',
    ),
  );
  $items["incubator_main"] = $openlayers_maps;
  return $items;
}
